name: MySQL Backup CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        VERSION: 1.0.0
        IMAGE: dqmdz/mysql-backup
        TAGS: ${VERSION}, latest
      run: docker build . --file Dockerfile --tag ${IMAGE}:latest
