name: MySQL Backup CI

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  VERSION: 1.0.0
  IMAGE: dqmdz/mysql-backup
  TAG: "${GITHUB_REF#refs/heads/}.$(git rev-parse --short ${GITHUB_SHA})"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE:latest --tag $IMAGE:$VERSION --tag $IMAGE:$TAG
    - name: Docker push
      run: docker push $IMAGE:latest && docker push $IMAGE:$VERSION && docker push $IMAGE:$TAG
